
enum BowlResult{DOT_BALL, Single, NOBALL, WIDEBALL, BYES, WICKET};
enum WicketType{BOWLED, CAOUGTH, CAUGHTANDBOWL, LBW, RUNOUT, STUMP, FIELDVOILATION, RETIREDOUT};
enum BowlType{FASTBALL, SPIN, MEDIUMPACE};
enum PlayerType{BATTER, BOWLER, ALLROUNDER};
enum BatterType{RIGHT_HAND, LEFT_HAND};
enum BowlerType{RIGHT_HAND_SPIN, LEFT_HAND_SPIN, RIGHT_HAND_FAST_BOWLER, LEFT_HAND_FAST_BOWLER};

